
package com.reportingsales;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DeFactoSF1Soap", targetNamespace = "http://reportingsales.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DeFactoSF1Soap {


    /**
     * 
     * @param zip
     * @param key
     * @return
     *     returns com.reportingsales.DefactoZip2
     */
    @WebMethod(operationName = "DeFactoSF1Part2ByZip", action = "http://reportingsales.com/DeFactoSF1Part2ByZip")
    @WebResult(name = "DeFactoSF1Part2ByZipResult", targetNamespace = "http://reportingsales.com/")
    @RequestWrapper(localName = "DeFactoSF1Part2ByZip", targetNamespace = "http://reportingsales.com/", className = "com.reportingsales.DeFactoSF1Part2ByZip")
    @ResponseWrapper(localName = "DeFactoSF1Part2ByZipResponse", targetNamespace = "http://reportingsales.com/", className = "com.reportingsales.DeFactoSF1Part2ByZipResponse")
    public DefactoZip2 deFactoSF1Part2ByZip(
        @WebParam(name = "zip", targetNamespace = "http://reportingsales.com/")
        String zip,
        @WebParam(name = "key", targetNamespace = "http://reportingsales.com/")
        String key);

    /**
     * 
     * @param zip
     * @param key
     * @return
     *     returns com.reportingsales.BigZip
     */
    @WebMethod(operationName = "DeFactoSF1Part1ByZip", action = "http://reportingsales.com/DeFactoSF1Part1ByZip")
    @WebResult(name = "DeFactoSF1Part1ByZipResult", targetNamespace = "http://reportingsales.com/")
    @RequestWrapper(localName = "DeFactoSF1Part1ByZip", targetNamespace = "http://reportingsales.com/", className = "com.reportingsales.DeFactoSF1Part1ByZip")
    @ResponseWrapper(localName = "DeFactoSF1Part1ByZipResponse", targetNamespace = "http://reportingsales.com/", className = "com.reportingsales.DeFactoSF1Part1ByZipResponse")
    public BigZip deFactoSF1Part1ByZip(
        @WebParam(name = "zip", targetNamespace = "http://reportingsales.com/")
        String zip,
        @WebParam(name = "key", targetNamespace = "http://reportingsales.com/")
        String key);

    /**
     * 
     * @param place
     * @param state
     * @param key
     * @return
     *     returns com.reportingsales.BigName
     */
    @WebMethod(operationName = "DeFactoSF1Part1ByNameState", action = "http://reportingsales.com/DeFactoSF1Part1ByNameState")
    @WebResult(name = "DeFactoSF1Part1ByNameStateResult", targetNamespace = "http://reportingsales.com/")
    @RequestWrapper(localName = "DeFactoSF1Part1ByNameState", targetNamespace = "http://reportingsales.com/", className = "com.reportingsales.DeFactoSF1Part1ByNameState")
    @ResponseWrapper(localName = "DeFactoSF1Part1ByNameStateResponse", targetNamespace = "http://reportingsales.com/", className = "com.reportingsales.DeFactoSF1Part1ByNameStateResponse")
    public BigName deFactoSF1Part1ByNameState(
        @WebParam(name = "place", targetNamespace = "http://reportingsales.com/")
        String place,
        @WebParam(name = "state", targetNamespace = "http://reportingsales.com/")
        String state,
        @WebParam(name = "key", targetNamespace = "http://reportingsales.com/")
        String key);

    /**
     * 
     * @param place
     * @param state
     * @param key
     * @return
     *     returns com.reportingsales.ArrayOfDefactoName2
     */
    @WebMethod(operationName = "DeFactoSF1Part2ByNameState", action = "http://reportingsales.com/DeFactoSF1Part2ByNameState")
    @WebResult(name = "DeFactoSF1Part2ByNameStateResult", targetNamespace = "http://reportingsales.com/")
    @RequestWrapper(localName = "DeFactoSF1Part2ByNameState", targetNamespace = "http://reportingsales.com/", className = "com.reportingsales.DeFactoSF1Part2ByNameState")
    @ResponseWrapper(localName = "DeFactoSF1Part2ByNameStateResponse", targetNamespace = "http://reportingsales.com/", className = "com.reportingsales.DeFactoSF1Part2ByNameStateResponse")
    public ArrayOfDefactoName2 deFactoSF1Part2ByNameState(
        @WebParam(name = "place", targetNamespace = "http://reportingsales.com/")
        String place,
        @WebParam(name = "state", targetNamespace = "http://reportingsales.com/")
        String state,
        @WebParam(name = "key", targetNamespace = "http://reportingsales.com/")
        String key);

}
