
package com.reportingsales;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DeFactoSF1HttpGet", targetNamespace = "http://reportingsales.com/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DeFactoSF1HttpGet {


    /**
     * 
     * @param zip
     * @param key
     * @return
     *     returns com.reportingsales.DefactoZip2
     */
    @WebMethod(operationName = "DeFactoSF1Part2ByZip")
    @WebResult(name = "DefactoZip2", targetNamespace = "http://reportingsales.com/", partName = "Body")
    public DefactoZip2 deFactoSF1Part2ByZip(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "zip")
        String zip,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "key")
        String key);

    /**
     * 
     * @param zip
     * @param key
     * @return
     *     returns com.reportingsales.BigZip
     */
    @WebMethod(operationName = "DeFactoSF1Part1ByZip")
    @WebResult(name = "bigZip", targetNamespace = "http://reportingsales.com/", partName = "Body")
    public BigZip deFactoSF1Part1ByZip(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "zip")
        String zip,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "key")
        String key);

    /**
     * 
     * @param place
     * @param state
     * @param key
     * @return
     *     returns com.reportingsales.BigName
     */
    @WebMethod(operationName = "DeFactoSF1Part1ByNameState")
    @WebResult(name = "bigName", targetNamespace = "http://reportingsales.com/", partName = "Body")
    public BigName deFactoSF1Part1ByNameState(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "place")
        String place,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "state")
        String state,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "key")
        String key);

    /**
     * 
     * @param place
     * @param state
     * @param key
     * @return
     *     returns com.reportingsales.ArrayOfDefactoName2
     */
    @WebMethod(operationName = "DeFactoSF1Part2ByNameState")
    @WebResult(name = "ArrayOfDefactoName2", targetNamespace = "http://reportingsales.com/", partName = "Body")
    public ArrayOfDefactoName2 deFactoSF1Part2ByNameState(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "place")
        String place,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "state")
        String state,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "key")
        String key);

}
