
package com.reportingsales;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DeFactoSF1", targetNamespace = "http://reportingsales.com/", wsdlLocation = "http://www.reportingsales.com/DeFactoSF1.asmx?WSDL")
public class DeFactoSF1
    extends Service
{

    private final static URL DEFACTOSF1_WSDL_LOCATION;
    private final static WebServiceException DEFACTOSF1_EXCEPTION;
    private final static QName DEFACTOSF1_QNAME = new QName("http://reportingsales.com/", "DeFactoSF1");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www.reportingsales.com/DeFactoSF1.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DEFACTOSF1_WSDL_LOCATION = url;
        DEFACTOSF1_EXCEPTION = e;
    }

    public DeFactoSF1() {
        super(__getWsdlLocation(), DEFACTOSF1_QNAME);
    }

    public DeFactoSF1(WebServiceFeature... features) {
        super(__getWsdlLocation(), DEFACTOSF1_QNAME, features);
    }

    public DeFactoSF1(URL wsdlLocation) {
        super(wsdlLocation, DEFACTOSF1_QNAME);
    }

    public DeFactoSF1(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DEFACTOSF1_QNAME, features);
    }

    public DeFactoSF1(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DeFactoSF1(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DeFactoSF1Soap
     */
    @WebEndpoint(name = "DeFactoSF1Soap")
    public DeFactoSF1Soap getDeFactoSF1Soap() {
        return super.getPort(new QName("http://reportingsales.com/", "DeFactoSF1Soap"), DeFactoSF1Soap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DeFactoSF1Soap
     */
    @WebEndpoint(name = "DeFactoSF1Soap")
    public DeFactoSF1Soap getDeFactoSF1Soap(WebServiceFeature... features) {
        return super.getPort(new QName("http://reportingsales.com/", "DeFactoSF1Soap"), DeFactoSF1Soap.class, features);
    }

    /**
     * 
     * @return
     *     returns DeFactoSF1Soap
     */
    @WebEndpoint(name = "DeFactoSF1Soap12")
    public DeFactoSF1Soap getDeFactoSF1Soap12() {
        return super.getPort(new QName("http://reportingsales.com/", "DeFactoSF1Soap12"), DeFactoSF1Soap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DeFactoSF1Soap
     */
    @WebEndpoint(name = "DeFactoSF1Soap12")
    public DeFactoSF1Soap getDeFactoSF1Soap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://reportingsales.com/", "DeFactoSF1Soap12"), DeFactoSF1Soap.class, features);
    }

    /**
     * 
     * @return
     *     returns DeFactoSF1HttpGet
     */
    @WebEndpoint(name = "DeFactoSF1HttpGet")
    public DeFactoSF1HttpGet getDeFactoSF1HttpGet() {
        return super.getPort(new QName("http://reportingsales.com/", "DeFactoSF1HttpGet"), DeFactoSF1HttpGet.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DeFactoSF1HttpGet
     */
    @WebEndpoint(name = "DeFactoSF1HttpGet")
    public DeFactoSF1HttpGet getDeFactoSF1HttpGet(WebServiceFeature... features) {
        return super.getPort(new QName("http://reportingsales.com/", "DeFactoSF1HttpGet"), DeFactoSF1HttpGet.class, features);
    }

    /**
     * 
     * @return
     *     returns DeFactoSF1HttpPost
     */
    @WebEndpoint(name = "DeFactoSF1HttpPost")
    public DeFactoSF1HttpPost getDeFactoSF1HttpPost() {
        return super.getPort(new QName("http://reportingsales.com/", "DeFactoSF1HttpPost"), DeFactoSF1HttpPost.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DeFactoSF1HttpPost
     */
    @WebEndpoint(name = "DeFactoSF1HttpPost")
    public DeFactoSF1HttpPost getDeFactoSF1HttpPost(WebServiceFeature... features) {
        return super.getPort(new QName("http://reportingsales.com/", "DeFactoSF1HttpPost"), DeFactoSF1HttpPost.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DEFACTOSF1_EXCEPTION!= null) {
            throw DEFACTOSF1_EXCEPTION;
        }
        return DEFACTOSF1_WSDL_LOCATION;
    }

}
