
package com.jaxws.calc;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CalculateSumService", targetNamespace = "http://calc.jaxws.com/", wsdlLocation = "http://localhost:8080/JaxWsCalculate/CalculateSum?WSDL")
public class CalculateSumService
    extends Service
{

    private final static URL CALCULATESUMSERVICE_WSDL_LOCATION;
    private final static WebServiceException CALCULATESUMSERVICE_EXCEPTION;
    private final static QName CALCULATESUMSERVICE_QNAME = new QName("http://calc.jaxws.com/", "CalculateSumService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/JaxWsCalculate/CalculateSum?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALCULATESUMSERVICE_WSDL_LOCATION = url;
        CALCULATESUMSERVICE_EXCEPTION = e;
    }

    public CalculateSumService() {
        super(__getWsdlLocation(), CALCULATESUMSERVICE_QNAME);
    }

    public CalculateSumService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALCULATESUMSERVICE_QNAME, features);
    }

    public CalculateSumService(URL wsdlLocation) {
        super(wsdlLocation, CALCULATESUMSERVICE_QNAME);
    }

    public CalculateSumService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALCULATESUMSERVICE_QNAME, features);
    }

    public CalculateSumService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculateSumService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CalculateSum
     */
    @WebEndpoint(name = "CalculateSumPort")
    public CalculateSum getCalculateSumPort() {
        return super.getPort(new QName("http://calc.jaxws.com/", "CalculateSumPort"), CalculateSum.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalculateSum
     */
    @WebEndpoint(name = "CalculateSumPort")
    public CalculateSum getCalculateSumPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://calc.jaxws.com/", "CalculateSumPort"), CalculateSum.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALCULATESUMSERVICE_EXCEPTION!= null) {
            throw CALCULATESUMSERVICE_EXCEPTION;
        }
        return CALCULATESUMSERVICE_WSDL_LOCATION;
    }

}
